#!/bin/bash
#$ -A Dendrobatidae                # Charge project against directive
#$ -V                                    # Inherit submission environment
#$ -cwd                                # Use current working directory
#$ -N view-sort-index                  # Job name
#$ -j y                                  # Combine STDOUT and STDERR
#$ -o $JOB_NAME.o$JOB_ID           # Name of the output file (eg. myMPI.oJobID)
#$ -pe 2way 12                     # Request 24 processors, at a rate of 24 proc/node (so 1 node)
#$ -q normal                      # Use 'normal' queue ('development' for testing, 'largemem' for lots-o-memory)
#$ -l h_rt=24:00:00                 # Run time (hh:mm:ss)
#$ -M rdtarvin@gmail.com           # Email
#$ -m baes                            # Notifications at beginning and end of job


module load samtools

rm rs00*
samtools view -b -S rs.cat.sam > FILENAME.bam
samtools view -F 4 -f 2 -b FILENAME.bam > FILENAME_filtered.bam
samtools sort FILENAME_filtered.bam FILENAME_filtered.sorted
samtools index FILENAME_filtered.sorted.bam
